FROM debian:buster-slim AS build
RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev && \
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install gunicorn

#install requirements
COPY requirements.txt /requirements.txt
RUN /venv/bin/pip install --disable-pip-version-check -r /requirements.txt

# Create distroless img
FROM gcr.io/distroless/python3-debian10
COPY --from=build /venv /venv
COPY . /app
WORKDIR /app
ENTRYPOINT ["/venv/bin/gunicorn", "-b", "0.0.0.0:5000", "app:app"]